version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.159.1/hugo_extended_0.159.1_linux-amd64.tar.gz
      - tar -xzf hugo_extended_0.159.1_linux-amd64.tar.gz
      - chmod +x hugo
      - mv hugo /usr/local/bin/hugo
      - hugo version
  build:
    commands:
      - hugo
artifacts:
  base-directory: public
  files:
    - '**/*'